### ISSUE TITLE
[Enhancement] - Method to resolve the dynamic object

### ISSUE THREAD

**Issue by KhanMechAI** [childsish/dynamic-yaml#15] opened 2021-11-09 07:13 UTC
Ran into the issue when trying to pass in a list to a pandas dataframe. I was trying to define some columns, but the list of columns wouldn't resolve. See below example:

```python
import dynamic_yaml
import pandas as pd

yml = '''
names:
  n1: "name1"
  n2: "name2"
columns:
  - "{names.n1}"
  - "{names.n2}"
'''


if __name__ == '__main__':
    config = dynamic_yaml.load(yml)

    df = pd.DataFrame(columns=config.columns)

    print(df.columns)
```
Yeilds:
```
Index(['{names.n1}', '{names.n2}'], dtype='object')
```

So either after a fix that resolves the object when passed, or a method I can call on the object such as `config.columns.as_list()` or `config.columns.as_set()` or `config.columns.resolve()`. Not sure what the best approach is.

Current approach is to unpack and store in a variable. Roughly the following:
```python
cols = [config.columns[x] for x in range(len(config.columns))]
```

**Comment by KhanMechAI** [comment] 2021-11-09 07:15
I should also say, willing to contribute just point me in the right direction

**Comment by KhanMechAI** [comment] 2021-11-09 07:26
Actually, it'd be good if it could resolve it to a dictionary also.  So at an arbitrary point in the tree, it could return the dict of keys and values.

**Comment by KhanMechAI** [comment] 2021-11-10 04:50
I was having issues with nested lists, so I've written this little class to resolve an arbitrary object. Not an ideal way of doing it, especially comparing to the class name string, but I didnt have access to the types/cbb to try and load them. this should work for at least the two classes `YamlList` and `YamlDict`

```python
class DynamicResolver:
    yaml_list_type = "YamlList"
    yaml_dict_type = "YamlDict"

    @staticmethod
    def _get_type_string(obj):
        return obj.__class__.__name__

    @staticmethod
    def _resolve_dictionary(dyn_list):
        return {k: v for k, v in dyn_list.items()}

    @staticmethod
    def _resolve_list(dyn_dict):
        return [dyn_dict[x] for x in range(len(dyn_dict))]

    @classmethod
    def _resolve_dynamic_yaml_object(cls, d_yml_ob):
        obj_type: str = cls._get_type_string(d_yml_ob)

        if obj_type == cls.yaml_list_type:
            partial_resovled_list = cls._resolve_list(d_yml_ob)
            fully_resolved_list = []
            for element in partial_resovled_list:
                fully_resolved_list.append(cls._resolve_dynamic_yaml_object(element))

            return fully_resolved_list
        elif obj_type == cls.yaml_dict_type:
            partial_resovled_dict = cls._resolve_dictionary(d_yml_ob)
            fully_resolved_dict = {}
            for k, v in partial_resovled_dict.items():
                fully_resolved_dict[k] = cls._resolve_dynamic_yaml_object(v)
            return fully_resolved_dict
        else:
            return d_yml_ob

    @classmethod
    def resolve(cls, dynamic_yaml_object):
        return cls._resolve_dynamic_yaml_object(dynamic_yaml_object)
```

**Comment by childsish** [comment] 2021-11-10 22:26
It turns out that adding an `__iter__` function to YamlList appears to solve your problem. Do you think you could try commit d19aa690d655069def26d93274fcaebbaafabf91 to check?

**Comment by KhanMechAI** [comment] 2021-11-10 22:31
Hah! Much more elegant. I'll give it a shot now

**Comment by KhanMechAI** [comment] 2021-11-10 22:50
Hey, seems to has solved that one, but opened up another issue:
```python
File "C:\Anaconda3\envs\client-dashboard\lib\site-packages\xlsxwriter\worksheet.py", line 2134, in data_validation
    options = options.copy()
  File "C:\Anaconda3\envs\client-dashboard\lib\site-packages\dynamic_yaml\yaml_wrappers.py", line 64, in __getattr__
    return super().__getattribute__(key)
AttributeError: 'YamlDict' object has no attribute 'copy'
```
I'm passing options into the `xlsxwriter` package also, which by the looks needs to copy it so it doesnt modify the base data.

**Comment by childsish** [comment] 2021-11-11 10:46
That sounds like a new issue, so I've opened a new one. Please post a minimal, reproducible example like the one you did for this example, in issue #17. I'll close this issue when I merge d19aa690d655069def26d93274fcaebbaafabf91.

**Closed** 2021-11-11 10:49 UTC
